version: '2'
services:
  nginx:
    image: nginx:latest
    environment:
      - SERVICE_STORE_WEB_HOSTNAME
      - SERVICE_STORE_WEB_PORT
    volumes:
      - "./config/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./config/nginx/default.template:/etc/nginx/conf.d/default.template"
    ports:
      - "80:80"
    restart: unless-stopped
    command: /bin/bash -c "envsubst '$$SERVICE_STORE_WEB_HOSTNAME:$$SERVICE_STORE_WEB_PORT' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

